spring:
  application:
    name: rest-with-spring-boot-java-v2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_java_v2?useTimezone=true&serverTimezone=UTC
    username: root
    password: "@Marce1234"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
server:
  port: 8081
logging:
  level:
    root: INFO
    #devcaleb.rest_with_spring_boot_java_v2: DEBUG
spring-doc:
  paths-to-match: /api/**/**
  swagger-ui:
    use-root-path: true
